language: android
android:
  components:
    - build-tools-25.0.3
    - android-23
env:
  BINTRAY_USER=edinaftctravis
  EDINAFTC_ARTIFACTORY_USER=travis
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
