language: android
android:
  components:
  - build-tools-25.0.3
  - android-23
env: BINTRAY_USER=edinaftctravis EDINAFTC_ARTIFACTORY_USER=travis
after_success:
  "./gradlew :NinevoltLib:javadoc"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache/"
notifications:
  slack:
    secure: fNCxdQC0QmGxn1w/C+ltlMPSORHQirurboKQ1HB258Ady5C9Ty7GHuBeb2P8G1SKWM4jHt+Wa2sN8jSPDZZj+0Eo7WExij1pwXRp/7npUKaIW6GMDwHWOerKLumbVn//kzLVhEUo5U0FP2Io25qQjt1X6p3j6QbCizrIMMvu+D6WluQ/QpLJkZuqlRZhed8SfiCuiV+dJazuY+h+cVaSAiid5FLchfZ8wx/mGhIM/jRC4qR3G4MHmCr0i+XSQ3bLk7b0SBq7OcuwkpAI3t0p+H1vP05klzKOEOC3ls7QXW6kSQj+sGS2ShzRw38WlQhMkolSuOrKZhWiDHLYQG+QW9Wt/NFHS3vz/zTmZwFm3ICwVXPk4pkjDygA4b4j3fr/p8Jh35V9Pmy78sBVFTnyg3Ipmus/LwO//gs8aqICvZ4T0EL+stv/rgZygqr2j4HVywJeW5WJ4ccxUIPGAVUnTXdMPPhzPWsO6R76IK7dRsE//ouaQbHxHOGSUygXCrkVEo9JcPlDi8NEZbWLVhslFzhH1avY8+TWBdFDdAkRZ/oBtqzIVws5rlf+3WUlnyVmuwRtYGC00WxHaqqG+DBzHKo32O64Y4n+WOXgtYvhRT3nejC+snR00SL8thq2wMCaSH0upOxbk4iTzcX6qkfoTaaOXeAktbxphTsxMnjvBP4=
  email:
    on_success: none
    on_failure: change
deploy:
  - provider: script
    script: .travis/ci-deploy.sh
    skip_cleanup: true
    on:
      repo: edinaftc/Ninevolt
      tags: true
  - provider: releases
    api_key:
      secure: t8SC+tflniXSJ2pt988ct0RvUDGKAjkUkCV8tl5ii5nC5tejtu+ho/kSl5XMltTC39D9WyO3+6pdeJ2K+h/q24nhO5WrL2FInVl3el3df50wPLIDsJIJMGENCMu7uagwy4vaDTLG6/fHA1XNL+epnzwrzy+iQFU/FtPlzEKp7NLNPe0VxsAGz4dzApgmOcbGNu4pqVm+cRrFPiKEy6QytEKC3n0pyULjKqdMp8luudLQsweFmb3mLbwkIm/SFAys4aHRrINS4NIh2dva0mpjr3KyH59VP0uodzrequfH0WYYB9IVqrLEQy4JJSINZQExBJcwO5OYqfuNL2zPr+WQPiA5XuBDSE8imk6xHK6p59oQx0T2bsGp8m/cUZ/l2xAWTS0LFWovuWUh7S7YWgncfQkpGh3240A020TBvP0fZcwYvmViGCwuTY2bjjEnxjBSTZ2oXkWzOi4ITFLE6COLufghP905nKVnpE2fIZjLGneC5BUajaYPcjmBAojfoUs76THVFKyh4DASGmVBK0tXk/LNJumFcEo4mtHYc994nWR5FVGu8tAj0Q4nTRDwgk/8bd5NtE1yV68+0vKMuFL0iRms8ypR+I7Rou8HyUxqC5f+XubTrs1MG+PuLIRSgEQ+CiHOQVaunGSzuV/cDDgI10DK1kN6sBqves3D/7gTBNU=
    file: NinevoltLib/build/outputs/aar/NinevoltLib-release.aar
    skip_cleanup: true
    on:
      repo: edinaftc/Ninevolt
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/
    name: Travis CI
    on:
      all_branches: true
